/** Labels shown in the CMS layout picker. Keep in sync with `pageBlocks` singular labels. */
export const PAGE_BLOCK_OPTIONS = [
  { slug: 'hero', label: 'Hero' },
  { slug: 'articles-hero', label: 'Articles Hero' },
  { slug: 'articles-featured', label: 'Articles Featured' },
  { slug: 'articles-index', label: 'Articles Index' },
  { slug: 'careers-hero', label: 'Careers Hero' },
  { slug: 'careers-index', label: 'Careers Index' },
  { slug: 'cs-hero', label: 'CS Banner' },
  { slug: 'cs-featured', label: 'CS Featured' },
  { slug: 'cs-index', label: 'CS Index' },
  { slug: 'cs-cta', label: 'CS CTA' },
  { slug: 'contact-hero', label: 'Contact Hero' },
  { slug: 'contact-process', label: 'Contact Process' },
  { slug: 'contact-channels', label: 'Contact Channels' },
  { slug: 'manifesto', label: 'Manifesto' },
  { slug: 'about-origin', label: 'About Origin' },
  { slug: 'about-story', label: 'About Story' },
  { slug: 'trust-indicators', label: 'Trust Indicators' },
  { slug: 'team', label: 'Team' },
  { slug: 'whats-new', label: 'Whats New' },
  { slug: 'distribution-network', label: 'Distribution Network' },
  { slug: 'faq-accordion', label: 'FAQ Accordion' },
  { slug: 'cta', label: 'CTA' },
  { slug: 'statistics', label: 'Statistics' },
  { slug: 'featured-products', label: 'Featured Products' },
  { slug: 'featured-industries', label: 'Featured Industries' },
  { slug: 'featured-services', label: 'Featured Services' },
  { slug: 'process-story', label: 'Process Story' },
  { slug: 'featured-case-studies', label: 'Featured Case Studies' },
  { slug: 'testimonials', label: 'Testimonials' },
  { slug: 'contact-preview', label: 'Contact Preview' },
  { slug: 'rich-content', label: 'Rich Content' },
  { slug: 'sustainability-hero', label: 'Sustainability Hero' },
  { slug: 'sustainability-impact', label: 'Sustainability Impact' },
  { slug: 'sustainability-circular', label: 'Sustainability Circular' },
  { slug: 'sustainability-drop', label: 'Sustainability Drop' },
  { slug: 'sustainability-numbers', label: 'Sustainability Numbers' },
  { slug: 'sustainability-applications', label: 'Sustainability Applications' },
  { slug: 'sustainability-cta', label: 'Sustainability CTA' },
  { slug: 'services-hero', label: 'Services Hero' },
  { slug: 'services-offerings', label: 'Services Offerings' },
  { slug: 'services-fluids', label: 'Services Fluids' },
  { slug: 'services-program', label: 'Services Program' },
  { slug: 'services-visit', label: 'Services Visit' },
  { slug: 'services-industries', label: 'Services Industries' },
  { slug: 'services-cta', label: 'Services CTA' },
  { slug: 'amc-hero', label: 'AMC Hero' },
  { slug: 'amc-why', label: 'AMC Why' },
  { slug: 'amc-coverage', label: 'AMC Coverage' },
  { slug: 'amc-visit', label: 'AMC Visit' },
  { slug: 'amc-industries', label: 'AMC Industries' },
  { slug: 'amc-proof', label: 'AMC Proof' },
  { slug: 'amc-cta', label: 'AMC CTA' },
] as const;

export type PageBlockSlug = (typeof PAGE_BLOCK_OPTIONS)[number]['slug'];
