/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'contact-info': ContactInfo;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Super Admins manage users and site configuration. Editors manage content.
   */
  role: 'super-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            /**
             * Primary hero headline. Use line breaks for multi-line titles.
             */
            headline: string;
            subheadline?: string | null;
            image?: (number | null) | Media;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Absolute URL or site path (e.g. /products or https://example.com).
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            metaStats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  logo: number | Media;
                  alt?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trust-indicators';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Absolute URL or site path (e.g. /products or https://example.com).
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-industries';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Absolute URL or site path (e.g. /products or https://example.com).
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-services';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  year?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process-story';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Absolute URL or site path (e.g. /products or https://example.com).
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-case-studies';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            quote?: string | null;
            quoteAuthor?: string | null;
            quoteRole?: string | null;
            image?: (number | null) | Media;
            timeline?:
              | {
                  year?: string | null;
                  label?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-story';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  quote: string;
                  clientName: string;
                  company?: string | null;
                  position?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            members?:
              | {
                  name: string;
                  role: string;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            subtext?: string | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Absolute URL or site path (e.g. /products or https://example.com).
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            trustBadges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            showContactInfo?: boolean | null;
            /**
             * Form UI will wire to the submission API in a later milestone.
             */
            showForm?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-preview';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-content';
          }
      )[]
    | null;
  /**
   * Search engine and social sharing metadata for this document.
   */
  seo?: {
    /**
     * Overrides the default page title in search results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Optional override. Leave blank to use the default URL.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              image?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              metaStats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'trust-indicators'?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    alt?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-industries'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'featured-services'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'process-story'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-case-studies'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-story'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              quote?: T;
              quoteAuthor?: T;
              quoteRole?: T;
              image?: T;
              timeline?:
                | T
                | {
                    year?: T;
                    label?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    quote?: T;
                    clientName?: T;
                    company?: T;
                    position?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              subtext?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-preview'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              showContactInfo?: T;
              showForm?: T;
              id?: T;
              blockName?: T;
            };
        'rich-content'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  companyTagline?: string | null;
  logo?: (number | null) | Media;
  logoMark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  defaultCta: {
    type: 'page' | 'custom';
    label?: string | null;
    page?: (number | null) | Page;
    /**
     * Absolute URL or site path (e.g. /products or https://example.com).
     */
    url?: string | null;
    openInNewTab?: boolean | null;
    appearance?: ('primary' | 'secondary' | 'ghost') | null;
  };
  fonts?: {
    headingFont?: string | null;
    bodyFont?: string | null;
  };
  theme?: {
    /**
     * CSS color value (hex recommended).
     */
    brandPrimary?: string | null;
    brandDeep?: string | null;
    brandBright?: string | null;
    background?: string | null;
    surface?: string | null;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  features?: {
    enableSearch?: boolean | null;
    enableBlog?: boolean | null;
    enableNewsletter?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Optional nested links (one level).
         */
        children?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Right-side items such as Contact CTA. Search is controlled by Site Settings features.
   */
  utilityMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Leave empty to reuse the main menu on mobile.
   */
  mobileMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Optional nested links (one level).
         */
        children?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    description?: string | null;
    placeholder?: string | null;
    /**
     * Show newsletter UI. Submission backend is deferred.
     */
    enabled?: boolean | null;
  };
  bottomBar?: {
    /**
     * Use {{year}} to insert the current year automatically.
     */
    copyrightText?: string | null;
    legalLinks?:
      | {
          label: string;
          type: 'page' | 'custom';
          page?: (number | null) | Page;
          url?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  certifications?:
    | {
        label: string;
        image?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  addresses?:
    | {
        label: string;
        street?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        pin?: string | null;
        mapLink?: string | null;
        id?: string | null;
      }[]
    | null;
  phones?:
    | {
        label: string;
        number: string;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        label: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  businessHours?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Google Maps embed URL (not the full iframe HTML).
   */
  mapEmbed?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * Use %s as the page title placeholder.
   */
  siteTitle?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Without the @ symbol.
   */
  twitterHandle?: string | null;
  googleSiteVerification?: string | null;
  structuredData?: {
    organizationName?: string | null;
    legalName?: string | null;
    /**
     * YYYY or YYYY-MM-DD
     */
    foundingDate?: string | null;
    url?: string | null;
    logo?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  companyTagline?: T;
  logo?: T;
  logoMark?: T;
  favicon?: T;
  defaultCta?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        appearance?: T;
      };
  fonts?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
      };
  theme?:
    | T
    | {
        brandPrimary?: T;
        brandDeep?: T;
        brandBright?: T;
        background?: T;
        surface?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  features?:
    | T
    | {
        enableSearch?: T;
        enableBlog?: T;
        enableNewsletter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  utilityMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  mobileMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        description?: T;
        placeholder?: T;
        enabled?: T;
      };
  bottomBar?:
    | T
    | {
        copyrightText?: T;
        legalLinks?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
      };
  certifications?:
    | T
    | {
        label?: T;
        image?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        city?: T;
        state?: T;
        country?: T;
        pin?: T;
        mapLink?: T;
        id?: T;
      };
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        label?: T;
        email?: T;
        id?: T;
      };
  businessHours?: T;
  mapEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  twitterHandle?: T;
  googleSiteVerification?: T;
  structuredData?:
    | T
    | {
        organizationName?: T;
        legalName?: T;
        foundingDate?: T;
        url?: T;
        logo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}