/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    jobs: Job;
    'product-templates': ProductTemplate;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'product-templates': ProductTemplatesSelect<false> | ProductTemplatesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'contact-info': ContactInfo;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Super Admins manage users and site configuration. Editors manage content.
   */
  role: 'super-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Defaults to the image file name. Change anytime to customize.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            /**
             * Panel = split content + image. Immersive = full-bleed industrial hero used on About.
             */
            variant?: ('panel' | 'immersive') | null;
            eyebrow?: string | null;
            /**
             * Primary hero headline. Use line breaks for multi-line titles.
             */
            headline: string;
            subheadline?: string | null;
            image?: (number | null) | Media;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            metaStats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subheadline?: string | null;
            image?: (number | null) | Media;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'articles-hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Optional. Leave empty to feature the latest article automatically.
             */
            featuredPost?: (number | null) | Post;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articles-featured';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Every published article is included automatically. Add any article here to remove it from this section.
             */
            hiddenPosts?:
              | {
                  post: number | Post;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articles-index';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subheadline?: string | null;
            /**
             * Shown in the open-roles panel, e.g. Gurugram  ·  Delhi  ·  Mumbai  ·  Chennai.
             */
            cities?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'careers-hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Every posted role is included automatically. Add a job here to remove it from this section.
             */
            hiddenJobs?:
              | {
                  job: number | Job;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'careers-index';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifesto';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            bodySecondary?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            milestones?:
              | {
                  year: string;
                  title: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-origin';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            quote?: string | null;
            quoteAuthor?: string | null;
            quoteRole?: string | null;
            image?: (number | null) | Media;
            timeline?:
              | {
                  year?: string | null;
                  label?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-story';
          }
        | {
            heading?: string | null;
            /**
             * Place the heading on the left, center, or right of the rule line.
             */
            headingAlign?: ('left' | 'center' | 'right') | null;
            logos?:
              | {
                  logo: number | Media;
                  alt?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trust-indicators';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Portrait cards shown in the main row. Add a photo, name, and role.
             */
            members?:
              | {
                  name: string;
                  role: string;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Turn on to show the Operations & Specialists block grid below the portraits.
             */
            showExtraMembers?: boolean | null;
            /**
             * e.g. OPERATIONS & SPECIALISTS
             */
            extraHeading?: string | null;
            /**
             * Text-only blocks: name and role. No photo.
             */
            extraMembers?:
              | {
                  name: string;
                  role: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cards?:
              | {
                  badge?: string | null;
                  title: string;
                  description?: string | null;
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whats-new';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Turn off to hide the India map and keep stats, hubs, and HQ.
             */
            showMap?: boolean | null;
            /**
             * Leave empty to use the interactive India map. Upload only if you want a static image instead.
             */
            mapImage?: (number | null) | Media;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            regionalOffices?:
              | {
                  city: string;
                  region: string;
                  kind?: ('hq' | 'hub' | 'partner') | null;
                  /**
                   * Optional horizontal pin override as % of map width (0–100). Leave blank for city preset.
                   */
                  mapX?: number | null;
                  /**
                   * Optional vertical pin override as % of map height (0–100). Leave blank for city preset.
                   */
                  mapY?: number | null;
                  /**
                   * Optional. Paste a Google Maps place or directions URL. Shows an open-in-maps button on the hub card.
                   */
                  mapsUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            hq?: {
              label?: string | null;
              title?: string | null;
              address?: string | null;
              phone?: string | null;
              mobile?: string | null;
              email?: string | null;
            };
            hqImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'distribution-network';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  defaultOpen?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-accordion';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Supporting copy under the heading.
             */
            subtext?: string | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            trustBadges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            /**
             * Build cards manually. Optionally link a Product so Explore goes to that PDP; otherwise use Custom link.
             */
            cards?:
              | {
                  /**
                   * e.g. 01 / SYSTEM
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Optional. When set, the card links to this product’s detail page.
                   */
                  product?: (number | null) | Product;
                  /**
                   * Optional URL when no product is linked. Leave empty to keep the card not clickable.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * The special card at the end of the second row.
             */
            customEngineering?: {
              /**
               * e.g. 06 / Bespoke
               */
              tag?: string | null;
              title?: string | null;
              description?: string | null;
              /**
               * e.g. Speak with an engineer
               */
              ctaLabel?: string | null;
              /**
               * Optional. Leave empty to keep the card not clickable.
               */
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Shown in two rows of three. Tag, title, description, image, and link.
             */
            cards?:
              | {
                  /**
                   * e.g. 01 / INDUSTRY
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Optional. Leave empty to keep the card as text only (not clickable).
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-industries';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            /**
             * Tag, title, description, and link for each card.
             */
            cards?:
              | {
                  /**
                   * e.g. 01 / CONSULT
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional. Leave empty to keep the card as text only (not clickable).
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-services';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  year?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Pill under the description, e.g. PARTICULATE > 18μm.
                   */
                  spec?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process-story';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            cta: {
              type: 'page' | 'custom';
              label?: string | null;
              page?: (number | null) | Page;
              /**
               * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
               */
              url?: string | null;
              openInNewTab?: boolean | null;
              appearance?: ('primary' | 'secondary' | 'ghost') | null;
            };
            /**
             * Shown in two rows of two. Tag, title, description, link, and up to three stats.
             */
            cards?:
              | {
                  /**
                   * e.g. CASE STUDY / AUTOMOTIVE
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional. Leave empty to keep the card as text only (not clickable).
                   */
                  href?: string | null;
                  metrics?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-case-studies';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  quote: string;
                  clientName: string;
                  company?: string | null;
                  position?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            showContactInfo?: boolean | null;
            /**
             * Form UI will wire to the submission API in a later milestone.
             */
            showForm?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-preview';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-content';
          }
      )[]
    | null;
  /**
   * Search engine and social sharing metadata for this document.
   */
  seo?: {
    /**
     * Overrides the default page title in search results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Optional override. Leave blank to use the default URL.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Journal articles. New posts appear on the Articles listing automatically unless hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary used on article cards and the featured story.
   */
  excerpt?: string | null;
  /**
   * Shown as the card tag, e.g. FILTRATION or OIL COST.
   */
  category?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Shown in the article sidebar. Defaults to Kleenoil Engineering.
   */
  authorName?: string | null;
  /**
   * Short line under the author name.
   */
  authorRole?: string | null;
  /**
   * Leave empty to list every Heading 2/3 from the body. Add rows to pick which sections appear and how they are labelled.
   */
  tableOfContents?:
    | {
        label: string;
        /**
         * Paste the exact Heading 2/3 from the body this link should scroll to. Leave empty to match Link text.
         */
        heading?: string | null;
        id?: string | null;
      }[]
    | null;
  heroCta: {
    type: 'page' | 'custom';
    label?: string | null;
    page?: (number | null) | Page;
    /**
     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
     */
    url?: string | null;
    openInNewTab?: boolean | null;
  };
  sidebarCta: {
    heading?: string | null;
    description?: string | null;
    link: {
      type: 'page' | 'custom';
      label?: string | null;
      page?: (number | null) | Page;
      /**
       * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
       */
      url?: string | null;
      openInNewTab?: boolean | null;
    };
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedSection: {
    /**
     * Defaults to Keep reading.
     */
    eyebrow?: string | null;
    /**
     * Defaults to More from the journal.
     */
    heading?: string | null;
    viewAll: {
      type: 'page' | 'custom';
      label?: string | null;
      page?: (number | null) | Page;
      /**
       * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
       */
      url?: string | null;
      openInNewTab?: boolean | null;
      appearance?: ('primary' | 'secondary' | 'ghost') | null;
    };
    /**
     * Pick up to three. Leave empty to fill with the latest other articles automatically.
     */
    posts?:
      | {
          post: number | Post;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Split quotation band under related articles. Empty fields use the defaults from the design.
   */
  closingCta?: {
    eyebrow?: string | null;
    /**
     * Use a line break to split the heading onto two lines.
     */
    heading?: string | null;
    description?: string | null;
    ctas?:
      | {
          link: {
            type: 'page' | 'custom';
            label?: string | null;
            page?: (number | null) | Page;
            /**
             * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
             */
            url?: string | null;
            openInNewTab?: boolean | null;
            appearance?: ('primary' | 'secondary' | 'ghost') | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Search engine and social sharing metadata for this document.
   */
  seo?: {
    /**
     * Overrides the default page title in search results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Optional override. Leave blank to use the default URL.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  slug: string;
  publishedAt?: string | null;
  /**
   * On by default. Turn off to keep this article live but remove it from the journal grid.
   */
  showInJournal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Open roles. New postings appear on the Careers page automatically unless hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Job title on the card and in the modal, e.g. Service Engineer — Field.
   */
  title: string;
  /**
   * Card tag, e.g. ENGINEERING or SALES.
   */
  department?: string | null;
  /**
   * e.g. Gurugram or New Delhi.
   */
  location?: string | null;
  /**
   * e.g. Full-time or Contract.
   */
  employmentType?: string | null;
  /**
   * Short copy on the card. Truncated to two lines on the site.
   */
  excerpt?: string | null;
  /**
   * Full job description for the modal. Use headings, lists, and links as needed.
   */
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  apply: {
    type: 'page' | 'custom';
    label?: string | null;
    page?: (number | null) | Page;
    /**
     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
     */
    url?: string | null;
    openInNewTab?: boolean | null;
  };
  slug: string;
  publishedAt?: string | null;
  /**
   * On by default. Turn off to keep this posting but hide it from the grid.
   */
  showOnCareers?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * Used on product cards and listings.
   */
  shortDescription?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Highlight in listings and homepage modules.
   */
  featured?: boolean | null;
  /**
   * PDP section order and common content come from this template.
   */
  template: number | ProductTemplate;
  /**
   * Per-section Common/Custom toggle. Common pulls content from the selected template.
   */
  layout?:
    | (
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            /**
             * e.g. FLAGSHIP SYSTEM
             */
            badge?: string | null;
            /**
             * e.g. 01 / OIL FILTRATION SYSTEMS
             */
            eyebrow?: string | null;
            /**
             * Use line breaks for multi-line titles.
             */
            title?: string | null;
            summary?: string | null;
            /**
             * Select or upload multiple images at once. Reorder as needed.
             */
            gallery?: (number | Media)[] | null;
            /**
             * Auto fills the row from how many specs you add (max 4, then wraps). 1–4 lock that many cards per row.
             */
            quickSpecsPerRow?: ('auto' | 'one' | 'two' | 'three' | 'four') | null;
            quickSpecs?:
              | {
                  value: string;
                  label: string;
                  /**
                   * When enabled, the value counts up when this spec scrolls into view (works best with numeric values like 99.9% or 5×).
                   */
                  animateCounter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-hero';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            leftHeading?: string | null;
            leftDescription?: string | null;
            rightHeading?: string | null;
            rightDescription?: string | null;
            /**
             * Each row is an icon + label. Leave the toggle off for the left column, on for the right.
             */
            items?:
              | {
                  icon?: (number | null) | Media;
                  text: string;
                  onRight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-contamination';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  label: string;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-how-it-works';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            machines?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-machines';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            columns?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            models?:
              | {
                  name: string;
                  values?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-models';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            results?:
              | {
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  metrics?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-results';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Pick products to feature. Falls back to manual cards if empty.
             */
            products?: (number | Product)[] | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  href?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-related';
          }
        | {
            /**
             * Common uses the Product Template content for this section. Custom lets this product override it.
             */
            dataSource: 'common' | 'custom';
            eyebrow?: string | null;
            heading?: string | null;
            subtext?: string | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            trustBadges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-cta';
          }
      )[]
    | null;
  /**
   * Search engine and social sharing metadata for this document.
   */
  seo?: {
    /**
     * Overrides the default page title in search results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Optional override. Leave blank to use the default URL.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Shared PDP section layouts. Products pick a template and override sections as needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-templates".
 */
export interface ProductTemplate {
  id: number;
  name: string;
  slug: string;
  /**
   * Common section content for products using this template. Section order here defines the PDP.
   */
  layout?:
    | (
        | {
            /**
             * e.g. FLAGSHIP SYSTEM
             */
            badge?: string | null;
            /**
             * e.g. 01 / OIL FILTRATION SYSTEMS
             */
            eyebrow?: string | null;
            /**
             * Use line breaks for multi-line titles.
             */
            title?: string | null;
            summary?: string | null;
            /**
             * Select or upload multiple images at once. Reorder as needed.
             */
            gallery?: (number | Media)[] | null;
            /**
             * Auto fills the row from how many specs you add (max 4, then wraps). 1–4 lock that many cards per row.
             */
            quickSpecsPerRow?: ('auto' | 'one' | 'two' | 'three' | 'four') | null;
            quickSpecs?:
              | {
                  value: string;
                  label: string;
                  /**
                   * When enabled, the value counts up when this spec scrolls into view (works best with numeric values like 99.9% or 5×).
                   */
                  animateCounter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            leftHeading?: string | null;
            leftDescription?: string | null;
            rightHeading?: string | null;
            rightDescription?: string | null;
            /**
             * Each row is an icon + label. Leave the toggle off for the left column, on for the right.
             */
            items?:
              | {
                  icon?: (number | null) | Media;
                  text: string;
                  onRight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-contamination';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  label: string;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-how-it-works';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            machines?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-machines';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            columns?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            models?:
              | {
                  name: string;
                  values?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-models';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            results?:
              | {
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  metrics?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-results';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Pick products to feature. Falls back to manual cards if empty.
             */
            products?: (number | Product)[] | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  href?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-related';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subtext?: string | null;
            ctas?:
              | {
                  link: {
                    type: 'page' | 'custom';
                    label?: string | null;
                    page?: (number | null) | Page;
                    /**
                     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
                     */
                    url?: string | null;
                    openInNewTab?: boolean | null;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            trustBadges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdp-cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'product-templates';
        value: number | ProductTemplate;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              headline?: T;
              subheadline?: T;
              image?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              metaStats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'articles-hero'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheadline?: T;
              image?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'articles-featured'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              featuredPost?: T;
              id?: T;
              blockName?: T;
            };
        'articles-index'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              hiddenPosts?:
                | T
                | {
                    post?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'careers-hero'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheadline?: T;
              cities?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'careers-index'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              hiddenJobs?:
                | T
                | {
                    job?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        'about-origin'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              bodySecondary?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-story'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              quote?: T;
              quoteAuthor?: T;
              quoteRole?: T;
              image?: T;
              timeline?:
                | T
                | {
                    year?: T;
                    label?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'trust-indicators'?:
          | T
          | {
              heading?: T;
              headingAlign?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    alt?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    photo?: T;
                    id?: T;
                  };
              showExtraMembers?: T;
              extraHeading?: T;
              extraMembers?:
                | T
                | {
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'whats-new'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'distribution-network'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              showMap?: T;
              mapImage?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              regionalOffices?:
                | T
                | {
                    city?: T;
                    region?: T;
                    kind?: T;
                    mapX?: T;
                    mapY?: T;
                    mapsUrl?: T;
                    id?: T;
                  };
              hq?:
                | T
                | {
                    label?: T;
                    title?: T;
                    address?: T;
                    phone?: T;
                    mobile?: T;
                    email?: T;
                  };
              hqImage?: T;
              id?: T;
              blockName?: T;
            };
        'faq-accordion'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    defaultOpen?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              cards?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    product?: T;
                    href?: T;
                    id?: T;
                  };
              customEngineering?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    ctaLabel?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-industries'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-services'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              cards?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'process-story'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    spec?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-case-studies'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              cards?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    href?: T;
                    metrics?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    quote?: T;
                    clientName?: T;
                    company?: T;
                    position?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-preview'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              showContactInfo?: T;
              showForm?: T;
              id?: T;
              blockName?: T;
            };
        'rich-content'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  category?: T;
  featuredImage?: T;
  authorName?: T;
  authorRole?: T;
  tableOfContents?:
    | T
    | {
        label?: T;
        heading?: T;
        id?: T;
      };
  heroCta?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
      };
  sidebarCta?:
    | T
    | {
        heading?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
            };
      };
  content?: T;
  relatedSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        viewAll?:
          | T
          | {
              type?: T;
              label?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              appearance?: T;
            };
        posts?:
          | T
          | {
              post?: T;
              id?: T;
            };
      };
  closingCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctas?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    page?: T;
                    url?: T;
                    openInNewTab?: T;
                    appearance?: T;
                  };
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  slug?: T;
  publishedAt?: T;
  showInJournal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  excerpt?: T;
  details?: T;
  apply?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
      };
  slug?: T;
  publishedAt?: T;
  showOnCareers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-templates_select".
 */
export interface ProductTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  layout?:
    | T
    | {
        'pdp-hero'?:
          | T
          | {
              badge?: T;
              eyebrow?: T;
              title?: T;
              summary?: T;
              gallery?: T;
              quickSpecsPerRow?: T;
              quickSpecs?:
                | T
                | {
                    value?: T;
                    label?: T;
                    animateCounter?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-contamination'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              leftHeading?: T;
              leftDescription?: T;
              rightHeading?: T;
              rightDescription?: T;
              items?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    onRight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-how-it-works'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-machines'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              machines?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-models'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              columns?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              models?:
                | T
                | {
                    name?: T;
                    values?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-results'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              results?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    metrics?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-related'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              products?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-cta'?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  featuredImage?: T;
  featured?: T;
  template?: T;
  layout?:
    | T
    | {
        'pdp-hero'?:
          | T
          | {
              dataSource?: T;
              badge?: T;
              eyebrow?: T;
              title?: T;
              summary?: T;
              gallery?: T;
              quickSpecsPerRow?: T;
              quickSpecs?:
                | T
                | {
                    value?: T;
                    label?: T;
                    animateCounter?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-contamination'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              leftHeading?: T;
              leftDescription?: T;
              rightHeading?: T;
              rightDescription?: T;
              items?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    onRight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-how-it-works'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-machines'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              machines?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-models'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              columns?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              models?:
                | T
                | {
                    name?: T;
                    values?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-results'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              results?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    metrics?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-related'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              products?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pdp-cta'?:
          | T
          | {
              dataSource?: T;
              eyebrow?: T;
              heading?: T;
              subtext?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          page?: T;
                          url?: T;
                          openInNewTab?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  companyTagline?: string | null;
  logo?: (number | null) | Media;
  logoMark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  defaultCta: {
    type: 'page' | 'custom';
    label?: string | null;
    page?: (number | null) | Page;
    /**
     * Optional. Absolute URL or site path (e.g. /products). Leave empty to keep this as text only.
     */
    url?: string | null;
    openInNewTab?: boolean | null;
    appearance?: ('primary' | 'secondary' | 'ghost') | null;
  };
  fonts?: {
    headingFont?: string | null;
    bodyFont?: string | null;
  };
  theme?: {
    /**
     * CSS color value (hex recommended).
     */
    brandPrimary?: string | null;
    brandDeep?: string | null;
    brandBright?: string | null;
    background?: string | null;
    surface?: string | null;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  features?: {
    enableSearch?: boolean | null;
    enableBlog?: boolean | null;
    enableNewsletter?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Desktop: product grid with hover image swap. Mobile: the same products as a normal list.
         */
        enableMegaMenu?: boolean | null;
        /**
         * Each row picks one product. The first two images and the title are used.
         */
        megaProducts?:
          | {
              product: number | Product;
              id?: string | null;
            }[]
          | null;
        /**
         * Leave empty for auto — products spread equally and wrap by screen size.
         */
        productsPerRow?: number | null;
        /**
         * Optional nested links (one level). Hidden when mega dropdown is on.
         */
        children?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Right-side items such as Contact CTA. Search is controlled by Site Settings features.
   */
  utilityMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Leave empty to reuse the main menu on mobile.
   */
  mobileMenu?:
    | {
        label: string;
        type: 'page' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Optional nested links (one level).
         */
        children?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              type: 'page' | 'custom';
              page?: (number | null) | Page;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    description?: string | null;
    placeholder?: string | null;
    /**
     * Show newsletter UI. Submission backend is deferred.
     */
    enabled?: boolean | null;
  };
  bottomBar?: {
    /**
     * Use {{year}} to insert the current year automatically.
     */
    copyrightText?: string | null;
    legalLinks?:
      | {
          label: string;
          type: 'page' | 'custom';
          page?: (number | null) | Page;
          url?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  certifications?:
    | {
        label: string;
        image?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  addresses?:
    | {
        label: string;
        street?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        pin?: string | null;
        mapLink?: string | null;
        id?: string | null;
      }[]
    | null;
  phones?:
    | {
        label: string;
        number: string;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        label: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  businessHours?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Google Maps embed URL (not the full iframe HTML).
   */
  mapEmbed?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * Use %s as the page title placeholder.
   */
  siteTitle?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Without the @ symbol.
   */
  twitterHandle?: string | null;
  googleSiteVerification?: string | null;
  structuredData?: {
    organizationName?: string | null;
    legalName?: string | null;
    /**
     * YYYY or YYYY-MM-DD
     */
    foundingDate?: string | null;
    url?: string | null;
    logo?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  companyTagline?: T;
  logo?: T;
  logoMark?: T;
  favicon?: T;
  defaultCta?:
    | T
    | {
        type?: T;
        label?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        appearance?: T;
      };
  fonts?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
      };
  theme?:
    | T
    | {
        brandPrimary?: T;
        brandDeep?: T;
        brandBright?: T;
        background?: T;
        surface?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  features?:
    | T
    | {
        enableSearch?: T;
        enableBlog?: T;
        enableNewsletter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        enableMegaMenu?: T;
        megaProducts?:
          | T
          | {
              product?: T;
              id?: T;
            };
        productsPerRow?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  utilityMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  mobileMenu?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        description?: T;
        placeholder?: T;
        enabled?: T;
      };
  bottomBar?:
    | T
    | {
        copyrightText?: T;
        legalLinks?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
      };
  certifications?:
    | T
    | {
        label?: T;
        image?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        city?: T;
        state?: T;
        country?: T;
        pin?: T;
        mapLink?: T;
        id?: T;
      };
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        label?: T;
        email?: T;
        id?: T;
      };
  businessHours?: T;
  mapEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  twitterHandle?: T;
  googleSiteVerification?: T;
  structuredData?:
    | T
    | {
        organizationName?: T;
        legalName?: T;
        foundingDate?: T;
        url?: T;
        logo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}